import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header/Navbar";
import {
  getLoginUserDetails,
  getSession,
  logout,
} from "@/actions/authAction/authActions";
import UserProvider from "@/store/UserProvider";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


type User = {
  _id: string;
  name: string;
  email: string;
  role: string;
  passwordChangedAt: string;
  photo: string;
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
   const  user = await getLoginUserDetails();

  const userLogout = async() => {
    "use server";
      return await logout();
  }
  

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <UserProvider user={user ? { ...user.data.data } :  null}>
            <Navbar session={session} userLogout={userLogout} />
            <div className="pt-16 flex-1">{children}</div>
            <Footer />
          </UserProvider>
          <Toaster position="top-right"   />
        </div>
      </body>
    </html>
  );
}
