import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header/Navbar";
import {
  getLoginUserDetails,
  getSession,
} from "@/actions/authAction/authActions";
import UserProvider from "@/store/UserProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  const user = await getLoginUserDetails();

  if(!session && !user) {
    return (
      <html lang="en">
        <body className={inter.className}>
          {children}
        </body>
      </html>
    )
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider
          user={user ? { ...user.data.data, image: user.data.image } : null}
        >
        <Navbar session={session} />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
